DROP TABLE "x_inca_xx";
/* CREATE TABLE */
CREATE TABLE "x_inca_xx" (definition VARCHAR(100),
geometrie VARCHAR(100),
symbologie VARCHAR(100),
jeu_classe_entite VARCHAR(100),
classe_entite VARCHAR(100),
consigne VARCHAR(100));
/* INSERT QUERY */
INSERT INTO "x_inca_xx" VALUES
($$Adresse$$,$$P$$,$$ADRESSE$$,$$ADRESSE$$,$$a_adresse_XX$$),
($$Mur ou mur anti-bruit$$,$$L$$,$$MUR$$,$$BATI$$,$$b_bati_lin_XX$$),
($$Mur paravalanche$$,$$L$$,$$MUR_PARAVALANCHE$$,$$BATI$$,$$b_bati_lin_XX$$),
($$Mur de pierres sèches$$,$$L$$,$$MUR_PIERRES_SECHES$$,$$BATI$$,$$b_bati_lin_XX$$),
($$Mur de soutènement$$,$$L$$,$$MUR_SOUTENEMENT$$,$$BATI$$,$$b_bati_lin_XX$$),
($$Ruine linéaire$$,$$L$$,$$RUINE_LIN$$,$$BATI$$,$$b_bati_lin_XX$$),
($$Terrasse$$,$$L$$,$$TERRASSE$$,$$BATI$$,$$b_bati_lin_XX$$),
($$Borne$$,$$P$$,$$BORNE$$,$$BATI$$,$$b_bati_ponc_XX$$),
($$Borne frontière$$,$$P$$,$$BORNE_FRONTIERE$$,$$BATI$$,$$b_bati_ponc_XX$$),
($$Borne milliaire$$,$$P$$,$$BORNE_MILLIAIRE$$,$$BATI$$,$$b_bati_ponc_XX$$),
($$Borne de sauveté$$,$$P$$,$$BORNE_SAUVETE$$,$$BATI$$,$$b_bati_ponc_XX$$),
($$Hôpital ponctuel$$,$$P$$,$$HOPITAL_PONC$$,$$BATI$$,$$b_bati_ponc_XX$$),
($$Mine souterraine$$,$$P$$,$$MINE_SOUTERRAINE$$,$$BATI$$,$$b_bati_ponc_XX$$),
($$Etablissement scolaire$$,$$P$$,$$ETABLISSEMENT$$,$$BATI$$,$$b_bati_ponc_XX$$),
($$Préfecture$$,$$P$$,$$PREFECTURE$$,$$BATI$$,$$b_bati_ponc_XX$$),
($$Stade$$,$$P$$,$$STADE_PONC$$,$$BATI$$,$$b_bati_ponc_XX$$),
($$Arc de triomphe$$,$$S$$,$$ARC_TRIOMPHE_SURF$$,$$BATI$$,$$b_bati_surf_XX$$),
($$Arène/théâtre antique$$,$$S$$,$$ARENE_THEATRE$$,$$BATI$$,$$b_bati_surf_XX$$),
($$Bâtiment commercial$$,$$S$$,$$BATI_COMMERCIAL$$,$$BATI$$,$$b_bati_surf_XX$$),
($$Bâti gare surfacique$$,$$S$$,$$BATI_GARE$$,$$BATI$$,$$b_bati_surf_XX$$),
($$Bâtiment industriel$$,$$S$$,$$BATI_INDUSTRIEL$$,$$BATI$$,$$b_bati_surf_XX$$),
($$Bâti péage $$,$$S$$,$$BATI_PEAGE$$,$$BATI$$,$$b_bati_surf_XX$$),
($$Bâtiment public$$,$$S$$,$$BATI_PUBLIC$$,$$BATI$$,$$b_bati_surf_XX$$),
($$Bâtiment quelconque$$,$$S$$,$$BATI_QQUE$$,$$BATI$$,$$b_bati_surf_XX$$),
($$Bâtiment sportif$$,$$S$$,$$BATI_SPORTIF$$,$$BATI$$,$$b_bati_surf_XX$$),
($$Château surfacique$$,$$S$$,$$CHATEAU_SURF$$,$$BATI$$,$$b_bati_surf_XX$$),
($$Fortification surfacique$$,$$S$$,$$FORTIF_SURF$$,$$BATI$$,$$b_bati_surf_XX$$),
($$Hangar$$,$$S$$,$$HANGAR$$,$$BATI$$,$$b_bati_surf_XX$$),
($$Hangar commercial$$,$$S$$,$$HANGAR_COMMERCIAL$$,$$BATI$$,$$b_bati_surf_XX$$),
($$Hangar industriel$$,$$S$$,$$HANGAR_INDUSTRIEL$$,$$BATI$$,$$b_bati_surf_XX$$),
($$Hangar public$$,$$S$$,$$HANGAR_PUBLIC$$,$$BATI$$,$$b_bati_surf_XX$$),
($$Mairie PS : voir MAIRIE_ISOLEE dans b_localite pour 100K/250K$$,$$S$$,$$MAIRIE$$,$$BATI$$,$$b_bati_surf_XX$$),
($$Mairie annexe$$,$$S$$,$$MAIRIE_ANNEXE$$,$$BATI$$,$$b_bati_surf_XX$$),
($$Monument surfacique$$,$$S$$,$$MONUMENT_SURF$$,$$BATI$$,$$b_bati_surf_XX$$),
($$Tour  donjon ou moulin surfacique$$,$$S$$,$$TOUR_MOULIN_SURF$$,$$BATI$$,$$b_bati_surf_XX$$),
($$Bâtiment remarquable$$,$$S$$,$$BATI_REMARQUABLE$$,$$BATI$$,$$b_bati_surf_XX$$),
($$Bâtiment au-dessus du routier (porche) à créer auto$$,$$S$$,$$BATI_SUP_ROUTIER$$,$$BATI$$,$$b_bati_surf_XX$$),
($$Bâtiment touristique surfacique Paris$$,$$S$$,$$BATI_TOURI_SURF$$,$$BATI$$,$$b_bati_surf_XX$$),
($$Cimetière militaire ponctuel (Nécropole)$$,$$P$$,$$CIMETIERE_MILI_PONC$$,$$BATI$$,$$b_cimetiere_ponc_XX$$),
($$Cimetière militaire surfacique $$,$$S$$,$$CIMETIERE_MILI_SURF$$,$$BATI$$,$$b_cimetiere_surf_XX$$),
($$Cimetière surfacique$$,$$S$$,$$CIMETIERE_SURF$$,$$BATI$$,$$b_cimetiere_surf_XX$$),
($$Nécropole nationale surfacique$$,$$S$$,$$NECROPOLE_NATIONALE$$,$$BATI$$,$$b_cimetiere_surf_XX$$),
($$Cimetière musulman surfacique$$,$$S$$,$$CIM_MUSULMAN$$,$$BATI$$,$$b_cimetiere_surf_XX$$),
($$Cimetière israelite surfacique$$,$$S$$,$$CIM_ISRAELITE$$,$$BATI$$,$$b_cimetiere_surf_XX$$),
($$Barrage linéaire$$,$$L$$,$$BARRAGE_LIN$$,$$BATI$$,$$b_hydro_lin_XX$$),
($$Digue$$,$$L$$,$$DIGUE$$,$$BATI$$,$$b_hydro_lin_XX$$),
($$Grue portuaire$$,$$L$$,$$GRUE_PORTUAIRE$$,$$BATI$$,$$b_hydro_lin_XX$$),
($$Pêche au carrelet$$,$$L$$,$$PECHE_AU_CARRELET$$,$$BATI$$,$$b_hydro_lin_XX$$),
($$Pêcherie linéaire$$,$$L$$,$$PECHERIE_LIN$$,$$BATI$$,$$b_hydro_lin_XX$$),
($$Portique portuaire$$,$$L$$,$$PORTIQUE_PORTUAIRE$$,$$BATI$$,$$b_hydro_lin_XX$$),
($$Quai linéaire$$,$$L$$,$$QUAI$$,$$BATI$$,$$b_hydro_lin_XX$$),
($$Abreuvoir$$,$$P$$,$$ABREUVOIR$$,$$BATI$$,$$b_hydro_ponc_XX$$),
($$Amer$$,$$P$$,$$AMER$$,$$BATI$$,$$b_hydro_ponc_XX$$),
($$Balise$$,$$P$$,$$BALISE$$,$$BATI$$,$$b_hydro_ponc_XX$$),
($$Barrage ponctuel$$,$$P$$,$$BARRAGE_PONC$$,$$BATI$$,$$b_hydro_ponc_XX$$),
($$Château d eau ponctuel$$,$$P$$,$$CHATEAU_EAU_PONC$$,$$BATI$$,$$b_hydro_ponc_XX$$),
($$Citerne ponctuelle$$,$$P$$,$$CITERNE$$,$$BATI$$,$$b_hydro_ponc_XX$$),
($$Ecluse ponctuelle$$,$$P$$,$$ECLUSE_PONC$$,$$BATI$$,$$b_hydro_ponc_XX$$),
($$Feu$$,$$P$$,$$FEU_PONC$$,$$BATI$$,$$b_hydro_ponc_XX$$),
($$Lavoir$$,$$P$$,$$LAVOIR$$,$$BATI$$,$$b_hydro_ponc_XX$$),
($$Phare$$,$$P$$,$$PHARE$$,$$BATI$$,$$b_hydro_ponc_XX$$),
($$Puits$$,$$P$$,$$PUITS$$,$$BATI$$,$$b_hydro_ponc_XX$$),
($$Réservoir d eau ponctuel$$,$$P$$,$$RESERVOIR_EAU_PONC$$,$$BATI$$,$$b_hydro_ponc_XX$$),
($$Station de pompage$$,$$P$$,$$STATION_DE_POMPAGE$$,$$BATI$$,$$b_hydro_ponc_XX$$),
($$Usine de traitement des eaux$$,$$P$$,$$STATION_EPURATION $$,$$BATI$$,$$b_hydro_ponc_XX$$),
($$Tourelle$$,$$P$$,$$TOURELLE$$,$$BATI$$,$$b_hydro_ponc_XX$$),
($$Tourelle lumineuse$$,$$P$$,$$TOURELLE_LUMINEUSE$$,$$BATI$$,$$b_hydro_ponc_XX$$),
($$Usine élévatrice$$,$$P$$,$$USINE_ELEVATRICE$$,$$BATI$$,$$b_hydro_ponc_XX$$),
($$Usine de production d eau potable$$,$$P$$,$$USINE_PRODUCTION_EAU$$,$$BATI$$,$$b_hydro_ponc_XX$$),
($$Barrage surfacique$$,$$S$$,$$BARRAGE_SURF$$,$$BATI$$,$$b_hydro_surf_XX$$),
($$Château d eau surfacique$$,$$S$$,$$CHATEAU_EAU_SURF$$,$$BATI$$,$$b_hydro_surf_XX$$),
($$Ecluse surfacique$$,$$S$$,$$ECLUSE_SURF$$,$$BATI$$,$$b_hydro_surf_XX$$),
($$Pêcherie surfacique$$,$$S$$,$$PECHERIE_SURF$$,$$BATI$$,$$b_hydro_surf_XX$$),
($$Réservoir d eau ou château d eau au sol surfacique$$,$$S$$,$$RESERVOIR_EAU_SURF$$,$$BATI$$,$$b_hydro_surf_XX$$),
($$Transport par câble$$,$$L$$,$$CABLE$$,$$BATI$$,$$b_infra_lin_XX$$),
($$Transport de matières premières (conduite  tapis roulant$$,$$L$$,$$CONDUITE_MATIERES_P$$,$$BATI$$,$$b_infra_lin_XX$$),
($$Conduite d hydrocarbures$$,$$L$$,$$HYDROCARBURES$$,$$BATI$$,$$b_infra_lin_XX$$),
($$Ligne électrique$$,$$L$$,$$LIGNE_ELECTRIQUE$$,$$BATI$$,$$b_infra_lin_XX$$),
($$Remontée mécanique/téléphérique$$,$$L$$,$$REMONTEE_MEC$$,$$BATI$$,$$b_infra_lin_XX$$),
($$Antenne ou pylône (non élec.) ponctuel$$,$$P$$,$$ANTENNE$$,$$BATI$$,$$b_infra_ponc_XX$$),
($$Cheminée$$,$$P$$,$$CHEMINEE$$,$$BATI$$,$$b_infra_ponc_XX$$),
($$Chevalement$$,$$P$$,$$CHEVALEMENT / CONSTR_INDIF_PONC$$,$$BATI$$,$$b_infra_ponc_XX$$),
($$Construction ponctuelle indifférenciée$$,$$P$$,$$CONSTR_INDIF_PONC$$,$$BATI$$,$$b_infra_ponc_XX$$),
($$Transformateur$$,$$P$$,$$CONSTR_SPE_TECHNIQUE$$,$$BATI$$,$$b_infra_ponc_XX$$),
($$Eolienne$$,$$P$$,$$EOLIENNE$$,$$BATI$$,$$b_infra_ponc_XX$$),
($$Poste gaz$$,$$P$$,$$POSTE_GAZ$$,$$BATI$$,$$b_infra_ponc_XX$$),
($$Puits de gaz$$,$$P$$,$$PUITS_GAZ$$,$$BATI$$,$$b_infra_ponc_XX$$),
($$Puits de pétrole$$,$$P$$,$$PUITS_PETROLE$$,$$BATI$$,$$b_infra_ponc_XX$$),
($$Pylone ligne électrique$$,$$P$$,$$PYLONE_ELEC$$,$$BATI$$,$$b_infra_ponc_XX$$),
($$Pylône météo$$,$$P$$,$$PYLONE_METEO$$,$$BATI$$,$$b_infra_ponc_XX$$),
($$Réservoir industriel ponctuel$$,$$P$$,$$RESERVOIR_PONC$$,$$BATI$$,$$b_infra_ponc_XX$$),
($$Silo ponctuel$$,$$P$$,$$SILO_PONC$$,$$BATI$$,$$b_infra_ponc_XX$$),
($$Torchère$$,$$P$$,$$TORCHERE$$,$$BATI$$,$$b_infra_ponc_XX$$),
($$Tour de guet$$,$$P$$,$$TOUR_GUET$$,$$BATI$$,$$b_infra_ponc_XX$$),
($$Tour hertzienne$$,$$P$$,$$TOUR_HERTZIENNE$$,$$BATI$$,$$b_infra_ponc_XX$$),
($$Poste électrique surfacique$$,$$S$$,$$POSTE_ELEC_SURF$$,$$BATI$$,$$b_infra_surf_XX$$),
($$Réservoir industriel surfacique$$,$$S$$,$$RESERVOIR_INDUS_SURF$$,$$BATI$$,$$b_infra_surf_XX$$),
($$Serre$$,$$S$$,$$SERRE_SURF$$,$$BATI$$,$$b_infra_surf_XX$$),
($$Silo industriel surfacique$$,$$S$$,$$SILO_SURF$$,$$BATI$$,$$b_infra_surf_XX$$),
($$Zone d habitation ponctuelle$$,$$P$$,$$LOCALITE_PONC$$,$$BATI$$,$$b_localite_xx$$),
($$Zone d habitation ponctuelle (secondaire)$$,$$P$$,$$LOCALITE_PONC_PETIT$$,$$BATI$$,$$b_localite_xx$$),
($$Mairie isolée (ponctuel)$$,$$P$$,$$MAIRIE_ISOLEE$$,$$BATI$$,$$b_localite_xx$$),
($$Bâtiment autre culte ponctuel$$,$$P$$,$$AUTRE_CULTE$$,$$BATI$$,$$b_religieux_ponc_XX$$),
($$Calvaire$$,$$P$$,$$CALVAIRE$$,$$BATI$$,$$b_religieux_ponc_XX$$),
($$Campanile$$,$$P$$,$$CAMPANILE$$,$$BATI$$,$$b_religieux_ponc_XX$$),
($$Chapelle ponctuelle (Bât. chrétien de moins de 10m de long) BDU2$$,$$P$$,$$CHAPELLE$$,$$BATI$$,$$b_religieux_ponc_XX$$),
($$??$$,$$P$$,$$CHRETIEN_PONC$$,$$BATI$$,$$b_religieux_ponc_XX$$),
($$Clocher$$,$$P$$,$$CLOCHER$$,$$BATI$$,$$b_religieux_ponc_XX$$),
($$Croix$$,$$P$$,$$CROIX$$,$$BATI$$,$$b_religieux_ponc_XX$$),
($$Eglise ponctuelle (Bâtiment chrétien de longueur entre 10 et 50 mètres)$$,$$P$$,$$EGLISE$$,$$BATI$$,$$b_religieux_ponc_XX$$),
($$??$$,$$P$$,$$MICRO_CHRETIEN_PONC$$,$$BATI$$,$$b_religieux_ponc_XX$$),
($$Minaret$$,$$P$$,$$MINARET$$,$$BATI$$,$$b_religieux_ponc_XX$$),
($$Mosquée ponctuelle$$,$$P$$,$$MOSQUEE$$,$$BATI$$,$$b_religieux_ponc_XX$$),
($$Oratoire$$,$$P$$,$$ORATOIRE_PONC$$,$$BATI$$,$$b_religieux_ponc_XX$$),
($$Statue religieuse$$,$$P$$,$$STATUE_RELIGIEUSE$$,$$BATI$$,$$b_religieux_ponc_XX$$),
($$Synagogue ponctuelle$$,$$P$$,$$SYNAGOGUE$$,$$BATI$$,$$b_religieux_ponc_XX$$),
($$Tombe isolée$$,$$P$$,$$TOMBE$$,$$BATI$$,$$b_religieux_ponc_XX$$),
($$Tombeau isolé$$,$$P$$,$$TOMBEAU$$,$$BATI$$,$$b_religieux_ponc_XX$$),
($$Vierge$$,$$P$$,$$VIERGE$$,$$BATI$$,$$b_religieux_ponc_XX$$),
($$Abbaye ponctuelle touristique$$,$$P$$,$$ABBAYE_T$$,$$BATI$$,$$b_religieux_ponc_XX$$),
($$Cathédrale ponctuelle touristique$$,$$P$$,$$CATHEDRALE_T$$,$$BATI$$,$$b_religieux_ponc_XX$$),
($$Chapelle ponctuelle touristique$$,$$P$$,$$CHAPELLE_T$$,$$BATI$$,$$b_religieux_ponc_XX$$),
($$Eglise ponctuelle touristique$$,$$P$$,$$EGLISE_T$$,$$BATI$$,$$b_religieux_ponc_XX$$),
($$Autre culte surfacique$$,$$S$$,$$AUTRE_CULTE_SURF$$,$$BATI$$,$$b_religieux_surf_XX$$),
($$Chapelle surfacique$$,$$S$$,$$CHAPELLE_SURF$$,$$BATI$$,$$b_religieux_surf_XX$$),
($$??$$,$$S$$,$$CHRETIEN_SURF$$,$$BATI$$,$$b_religieux_surf_XX$$),
($$Cathédrale/église surfacique$$,$$S$$,$$EGLISE_SURF$$,$$BATI$$,$$b_religieux_surf_XX$$),
($$Mosquée surfacique$$,$$S$$,$$MOSQUEE_SURF$$,$$BATI$$,$$b_religieux_surf_XX$$),
($$??$$,$$S$$,$$RELIGIEUX_QQUE$$,$$BATI$$,$$b_religieux_surf_XX$$),
($$Synagogue surfacique$$,$$S$$,$$SYNAGOGUE_SURF$$,$$BATI$$,$$b_religieux_surf_XX$$),
($$Arc de triomphe ponctuel??$$,$$P$$,$$ARC_TRIOMPHE_PONC$$,$$BATI$$,$$b_rem_ponc_XX$$),
($$Dolmen$$,$$P$$,$$DOLMEN$$,$$BATI$$,$$b_rem_ponc_XX$$),
($$Fortification ponctuelle non touristique (fort blockhaus casemate)$$,$$P$$,$$FORTIF_PONC$$,$$BATI$$,$$b_rem_ponc_XX$$),
($$Habitation troglodytique$$,$$P$$,$$HABITATION_TROGLO$$,$$BATI$$,$$b_rem_ponc_XX$$),
($$Menhir$$,$$P$$,$$MENHIR$$,$$BATI$$,$$b_rem_ponc_XX$$),
($$Monument ponctuel Double source 25K$$,$$P$$,$$MONUMENT_PONC$$,$$BATI$$,$$b_rem_ponc_XX$$),
($$??$$,$$P$$,$$MONUMENT_PONC_COMP$$,$$BATI$$,$$b_rem_ponc_XX$$),
($$Tour/donjon/moulin ponctuel$$,$$P$$,$$TOUR_MOULIN_PONC$$,$$BATI$$,$$b_rem_ponc_XX$$),
($$Bâtiment touristique ponctuel$$,$$P$$,$$BATI_TOURI_PONC_T$$,$$BATI$$,$$b_rem_ponc_XX$$),
($$Château touristique fermé au public$$,$$P$$,$$CHATEAU_FER_T$$,$$BATI$$,$$b_rem_ponc_XX$$),
($$Château ponctuel (non touristique)$$,$$P$$,$$CHATEAU_FOND_NT$$,$$BATI$$,$$b_rem_ponc_XX$$),
($$Château touristique ouvert au public$$,$$P$$,$$CHATEAU_OUV_T$$,$$BATI$$,$$b_rem_ponc_XX$$),
($$Edifice remarquable$$,$$P$$,$$EDIFICE_REMARQUABLE_T$$,$$BATI$$,$$b_rem_ponc_XX$$),
($$Fortification ponctuelle touristique Double source$$,$$P$$,$$FORTIF_PONC_T$$,$$BATI$$,$$b_rem_ponc_XX$$),
($$Maison du parc$$,$$P$$,$$MAISON_DU_PARC_T$$,$$BATI$$,$$b_rem_ponc_XX$$),
($$Mégalithe$$,$$P$$,$$MEGALITHE_T$$,$$BATI$$,$$b_rem_ponc_XX$$),
($$Ruine touristique deux sources$$,$$P$$,$$RUINE_T$$,$$BATI$$,$$b_rem_ponc_XX$$),
($$Site remarquable ponctuel $$,$$P$$,$$SITE_REM_PONC_T$$,$$BATI$$,$$b_rem_ponc_XX$$),
($$Vestiges antiques$$,$$P$$,$$VESTIGE_T$$,$$BATI$$,$$b_rem_ponc_XX$$),
($$Fronton de pelote basque$$,$$L$$,$$PELOTE_BASQ_LIN$$,$$BATI$$,$$b_sport_lin_XX$$),
($$Piste de bobsleigh$$,$$L$$,$$PISTE_BOBSLEIGH$$,$$BATI$$,$$b_sport_lin_XX$$),
($$Piste de luge$$,$$L$$,$$PISTE_LUGE$$,$$BATI$$,$$b_sport_lin_XX$$),
($$Sport de montagne$$,$$L$$,$$SPORT_MONTAGNE_LIN$$,$$BATI$$,$$b_sport_lin_XX$$),
($$Tremplin de saut à ski$$,$$L$$,$$TREMPLIN_SKI$$,$$BATI$$,$$b_sport_lin_XX$$),
($$Terrain de foot$$,$$S$$,$$FOOT_SURF$$,$$BATI$$,$$b_sport_surf_XX$$),
($$Petit terrain multi-sport$$,$$S$$,$$MULTI_SPORT_SURF$$,$$BATI$$,$$b_sport_surf_XX$$),
($$Bassin de natation$$,$$S$$,$$NATATION_SURF$$,$$BATI$$,$$b_sport_surf_XX$$),
($$Piste de sport$$,$$S$$,$$PISTE_SPORT_SURF$$,$$BATI$$,$$b_sport_surf_XX$$),
($$Terrain de sport indifférencié$$,$$S$$,$$SPORT_INDIF_SURF$$,$$BATI$$,$$b_sport_surf_XX$$),
($$Terrain de tennis$$,$$S$$,$$TENNIS_SURF$$,$$BATI$$,$$b_sport_surf_XX$$),
($$Croix église$$,$$L$$,$$CROIX_EGLISE$$,$$BATI$$,$$b_symbole_lin_XX$$),
($$Croix de serre$$,$$L$$,$$CROIX_SERRE$$,$$BATI$$,$$b_symbole_lin_XX$$),
($$Ligne médiane de terrain de football$$,$$L$$,$$LIGNE_FOOT$$,$$BATI$$,$$b_symbole_lin_XX$$),
($$Piste aérienne linéaire$$,$$L$$,$$PISTE_AERO_LIN$$,$$BATI$$,$$b_transport_lin_XX$$),
($$Aérodrome ponctuel$$,$$P$$,$$AERODROME_PONC$$,$$BATI$$,$$b_transport_ponc_XX$$),
($$Aérogare$$,$$P$$,$$AEROGARE_PONC$$,$$BATI$$,$$b_transport_ponc_XX$$),
($$Aéroport ponctuel$$,$$P$$,$$AEROPORT_PONC$$,$$BATI$$,$$b_transport_ponc_XX$$),
($$Gare non voyageurs (=gare fret uniquement)$$,$$P$$,$$GARE_NON_VOYAGEURS_PONC$$,$$BATI$$,$$b_transport_ponc_XX$$),
($$Gare (=gare/arret voyageur avec ou sans fret)$$,$$P$$,$$GARE_VOYAGEURS_PONC$$,$$BATI$$,$$b_transport_ponc_XX$$),
($$Station de métro$$,$$P$$,$$STATION_METRO$$,$$BATI$$,$$b_transport_ponc_XX$$),
($$Piste aérienne surfacique en dur$$,$$S$$,$$PISTE_DUR$$,$$BATI$$,$$b_transport_surf_XX$$),
($$Piste aérienne surfacique en herbe$$,$$S$$,$$PISTE_HERBE$$,$$BATI$$,$$b_transport_surf_XX$$),
($$Zone bâtie surfacique$$,$$S$$,$$[null]$$,$$BATI$$,$$b_zone_XX$$),
($$Zone industrielle et d activité surfacique$$,$$S$$,$$ZONE_INDUS_ACTI$$,$$BATI$$,$$b_zone_XX$$),
($$Écritures$$,$$S$$,$$NULL$$,$$ECRI$$,$$e_ecriture$$),
($$Aire de triage ferroviaire$$,$$S$$,$$AIRE_DE_TRIAGE$$,$$FERRE_XX$$,$$f_surf_XX$$),
($$Funiculaire ou crémaillère$$,$$L$$,$$FUNI_CREMAILLERE$$,$$FERRE_XX$$,$$f_voie_XX$$),
($$Transport urbain (métro ou tramway)$$,$$L$$,$$TRANSPORT_URBAIN$$,$$FERRE_XX$$,$$f_voie_XX$$),
($$Voie ferrée (non électrifiée) à 1 voie nb de voies existent au 250 > OACI$$,$$L$$,$$VF_1$$,$$FERRE_XX$$,$$f_voie_XX$$),
($$Voie ferrée (non électrifiée) à 2 voies DES LGV au 100K$$,$$L$$,$$VF_2$$,$$FERRE_XX$$,$$f_voie_XX$$),
($$Voie ferrée non électrifiée à 3 voies$$,$$L$$,$$VF_3$$,$$FERRE_XX$$,$$f_voie_XX$$),
($$Voie ferrée non électrifiée à 4 voies$$,$$L$$,$$VF_4$$,$$FERRE_XX$$,$$f_voie_XX$$),
($$Voie ferrée électrifiée à 1 voie distingable au 100K?$$,$$L$$,$$VF_ELEC_1$$,$$FERRE_XX$$,$$f_voie_XX$$),
($$Voie ferrée électrifiée à 2 voies distingable au 100K?$$,$$L$$,$$VF_ELEC_2$$,$$FERRE_XX$$,$$f_voie_XX$$),
($$Voie ferrée électrifiée à 3 voies$$,$$L$$,$$VF_ELEC_3$$,$$FERRE_XX$$,$$f_voie_XX$$),
($$Voie ferrée électrifiée à 4 voies$$,$$L$$,$$VF_ELEC_4$$,$$FERRE_XX$$,$$f_voie_XX$$),
($$Voie ferrée en construction$$,$$L$$,$$VF_EN_CONSTR$$,$$FERRE_XX$$,$$f_voie_XX$$),
($$Voie ferrée étroite à 1 voie$$,$$L$$,$$VF_ETROITE_1$$,$$FERRE_XX$$,$$f_voie_XX$$),
($$Voie ferrée étroite à 2 voies$$,$$L$$,$$VF_ETROITE_2$$,$$FERRE_XX$$,$$f_voie_XX$$),
($$Voie ferrée non exploitée$$,$$L$$,$$VF_NON_EXPLOITEE$$,$$FERRE_XX$$,$$f_voie_XX$$),
($$Voie ferrée de service$$,$$L$$,$$VF_SERVICE$$,$$FERRE_XX$$,$$f_voie_XX$$),
($$Tunnel funiculaire ou crémaillère$$,$$L$$,$$FUNI_CREMAILLERE_SOU$$,$$FERRE_XX$$,$$f_voie_sou_XX$$),
($$Tunnel transport urbain (métro ou tramway)$$,$$L$$,$$TRANSPORT_URBAIN_SOU$$,$$FERRE_XX$$,$$f_voie_sou_XX$$),
($$Tunnel voie ferrée (non électrifiée) à 1 voie$$,$$L$$,$$VF_1_SOU$$,$$FERRE_XX$$,$$f_voie_sou_XX$$),
($$Tunnel voie ferrée (non électrifiée) à 2 voies$$,$$L$$,$$VF_2_SOU$$,$$FERRE_XX$$,$$f_voie_sou_XX$$),
($$Tunnel voie ferrée (non électrifiée) à 3 voies$$,$$L$$,$$VF_3_SOU$$,$$FERRE_XX$$,$$f_voie_sou_XX$$),
($$Tunnel voie ferrée (non électrifiée) à 4 voies$$,$$L$$,$$VF_4_SOU$$,$$FERRE_XX$$,$$f_voie_sou_XX$$),
($$Tunnel voie ferrée électrifiée à 1 voie$$,$$L$$,$$VF_ELEC_1_SOU$$,$$FERRE_XX$$,$$f_voie_sou_XX$$),
($$Tunnel voie ferrée électrifiée à 2 voies$$,$$L$$,$$VF_ELEC_2_SOU$$,$$FERRE_XX$$,$$f_voie_sou_XX$$),
($$Tunnel voie ferrée électrifiée à 3 voies$$,$$L$$,$$VF_ELEC_3_SOU$$,$$FERRE_XX$$,$$f_voie_sou_XX$$),
($$Tunnel voie ferrée électrifiée à 4 voies$$,$$L$$,$$VF_ELEC_4_SOU$$,$$FERRE_XX$$,$$f_voie_sou_XX$$),
($$Tunnel voie ferrée étroite 1 voie$$,$$L$$,$$VF_ETROITE_1_SOU$$,$$FERRE_XX$$,$$f_voie_sou_XX$$),
($$Tunnel voie ferrée étroite 2 voies$$,$$L$$,$$VF_ETROITE_2_SOU$$,$$FERRE_XX$$,$$f_voie_sou_XX$$),
($$Tunnel ferro-routier (dont Sous la Manche)$$,$$L$$,$$VF_FERRO_ROUTIER_SOU$$,$$FERRE_XX$$,$$f_voie_sou_XX$$),
($$Tunnel de voie ferrée non exploitée$$,$$L$$,$$VF_NON_EXPLOITEE_SOU$$,$$FERRE_XX$$,$$f_voie_sou_XX$$),
($$Tunnel voie de service$$,$$L$$,$$VF_SERVICE_SOU$$,$$FERRE_XX$$,$$f_voie_sou_XX$$),
($$Passage supérieur funiculaire ou crémaillère$$,$$L$$,$$FUNI_CREMAILLERE_SUP$$,$$FERRE_XX$$,$$f_voie_sup_XX$$),
($$Passage supérieur transport urbain (métro ou tramway)$$,$$L$$,$$TRANSPORT_URBAIN_SUP$$,$$FERRE_XX$$,$$f_voie_sup_XX$$),
($$Passage supérieur voie ferrée (non électrifiée) à 1 voie (ou plus)$$,$$L$$,$$VF_1_SUP$$,$$FERRE_XX$$,$$f_voie_sup_XX$$),
($$Passage supérieur voie ferrée (non électrifiée) à 2 voies$$,$$L$$,$$VF_2_SUP$$,$$FERRE_XX$$,$$f_voie_sup_XX$$),
($$Passage supérieur voie ferrée (non électrifiée) à 3 voies$$,$$L$$,$$VF_3_SUP$$,$$FERRE_XX$$,$$f_voie_sup_XX$$),
($$Passage supérieur voie ferrée (non électrifiée) à 4 voies$$,$$L$$,$$VF_4_SUP$$,$$FERRE_XX$$,$$f_voie_sup_XX$$),
($$Passage supérieur voie ferrée électrifiée à 1 voie (ou plus)$$,$$L$$,$$VF_ELEC_1_SUP$$,$$FERRE_XX$$,$$f_voie_sup_XX$$),
($$Passage supérieur voie ferrée électrifiée à 2 voies$$,$$L$$,$$VF_ELEC_2_SUP$$,$$FERRE_XX$$,$$f_voie_sup_XX$$),
($$Passage supérieur voie ferrée électrifiée à 3 voies$$,$$L$$,$$VF_ELEC_3_SUP$$,$$FERRE_XX$$,$$f_voie_sup_XX$$),
($$Passage supérieur voie ferrée électrifiée à 4 voies$$,$$L$$,$$VF_ELEC_4_SUP$$,$$FERRE_XX$$,$$f_voie_sup_XX$$),
($$Passage supérieur de voie ferrée en construction$$,$$L$$,$$VF_EN_CONSTR_SUP$$,$$FERRE_XX$$,$$f_voie_sup_XX$$),
($$Passage supérieur voie ferrée étroite 1 voie$$,$$L$$,$$VF_ETROITE_1_SUP$$,$$FERRE_XX$$,$$f_voie_sup_XX$$),
($$Passage supérieur voie ferrée étroite 2 voies$$,$$L$$,$$VF_ETROITE_2_SUP$$,$$FERRE_XX$$,$$f_voie_sup_XX$$),
($$Passage supérieur de voie ferrée non exploitée$$,$$L$$,$$VF_NON_EXPLOITEE_SUP$$,$$FERRE_XX$$,$$f_voie_sup_XX$$),
($$Passage supérieur voie de service$$,$$L$$,$$VF_SERVICE_SUP$$,$$FERRE_XX$$,$$f_voie_sup_XX$$),
($$Complexe hydronyme linéaire$$,$$P$$,$$[null]$$,$$HYDROGRAPHIE_XX$$,$$h_cours_d_eau_XX$$),
($$Laisse de basses mers$$,$$L$$,$$LAISSE_BASSES_MERS$$,$$HYDROGRAPHIE_XX$$,$$h_laisse_XX$$),
($$Laisse (de hautes mers)$$,$$L$$,$$LAISSE_HAUTES_MERS$$,$$HYDROGRAPHIE_XX$$,$$h_laisse_XX$$),
($$Complexe hydronyme surfacique$$,$$S$$,$$PLAN_D_EAU$$,$$HYDROGRAPHIE_XX$$,$$h_plan_d_eau_XX$$),
($$Cascade$$,$$P$$,$$CASCADE$$,$$HYDROGRAPHIE_XX$$,$$h_ponc_XX$$),
($$Fontaine$$,$$P$$,$$FONTAINE$$,$$HYDROGRAPHIE_XX$$,$$h_ponc_XX$$),
($$Perte$$,$$P$$,$$PERTE$$,$$HYDROGRAPHIE_XX$$,$$h_ponc_XX$$),
($$Autre point d eau (Indifférencié)$$,$$P$$,$$POINT_D_EAU$$,$$HYDROGRAPHIE_XX$$,$$h_ponc_XX$$),
($$Résurgence$$,$$P$$,$$RESURGENCE$$,$$HYDROGRAPHIE_XX$$,$$h_ponc_XX$$),
($$Source (touristique au 100)$$,$$P$$,$$SOURCE$$,$$HYDROGRAPHIE_XX$$,$$h_ponc_XX$$),
($$Source captée$$,$$P$$,$$SOURCE_CAPTEE$$,$$HYDROGRAPHIE_XX$$,$$h_ponc_XX$$),
($$Aqueduc au sol$$,$$L$$,$$AQUEDUC_AU_SOL$$,$$HYDROGRAPHIE_XX$$,$$h_reseau_XX$$),
($$Canal linéaire$$,$$L$$,$$CANAL$$,$$HYDROGRAPHIE_XX$$,$$h_reseau_XX$$),
($$Cours d eau linéaire permanent (fin pour ME)$$,$$L$$,$$COURS_D_EAU$$,$$HYDROGRAPHIE_XX$$,$$h_reseau_XX$$),
($$Cours d eau linéaire permanent large$$,$$L$$,$$COURS_D_EAU_LAR$$,$$HYDROGRAPHIE_XX$$,$$h_reseau_XX$$),
($$Cours d eau linéaire permanent moyen$$,$$L$$,$$COURS_D_EAU_MOY$$,$$HYDROGRAPHIE_XX$$,$$h_reseau_XX$$),
($$Cours d eau linéaire temporaire (fin pour ME)$$,$$L$$,$$COURS_D_EAU_TEMP$$,$$HYDROGRAPHIE_XX$$,$$h_reseau_XX$$),
($$Cours d eau linéaire temporaire moyen$$,$$L$$,$$COURS_D_EAU_TEMP_MOY$$,$$HYDROGRAPHIE_XX$$,$$h_reseau_XX$$),
($$Aqueduc souterrain$$,$$L$$,$$AQUEDUC_SOU$$,$$HYDROGRAPHIE_XX$$,$$h_reseau_sou_XX$$),
($$Cours d eau linéaire souterrain permanent (fin pour ME)$$,$$L$$,$$COURS_D_EAU_SOU$$,$$HYDROGRAPHIE_XX$$,$$h_reseau_sou_XX$$),
($$Aqueduc en hauteur$$,$$L$$,$$AQUEDUC_SUP$$,$$HYDROGRAPHIE_XX$$,$$h_reseau_sup_XX$$),
($$Passage supérieur de canal linéaire$$,$$L$$,$$CANAL_SUP$$,$$HYDROGRAPHIE_XX$$,$$h_reseau_sup_XX$$),
($$Bassin surfacique$$,$$S$$,$$BASSIN$$,$$HYDROGRAPHIE_XX$$,$$h_surf_XX$$),
($$Surface d eau$$,$$S$$,$$SURFACE_D_EAU$$,$$HYDROGRAPHIE_XX$$,$$h_surf_XX$$),
($$Surface d eau souterraine$$,$$S$$,$$SURFACE_D_EAU_SOU$$,$$HYDROGRAPHIE_XX$$,$$h_surf_XX$$),
($$Surface d eau temporaire$$,$$S$$,$$SURFACE_D_EAU_TEMP$$,$$HYDROGRAPHIE_XX$$,$$h_surf_XX$$),
($$Zone d estran$$,$$S$$,$$ZONE_D_ESTRAN$$,$$HYDROGRAPHIE_XX$$,$$h_surf_XX$$),
($$Zone de marais (depuis déc 2020  avant OCS)$$,$$S$$,$$ZONE_MARAIS$$,$$HYDROGRAPHIE_XX$$,$$h_surf_XX$$),
($$Zone de marais salants (déc 2020  avant OCS)$$,$$S$$,$$ZONE_MARAIS_SALANT$$,$$HYDROGRAPHIE_XX$$,$$h_surf_XX$$),
($$Zone marine$$,$$S$$,$$ZONE_MARINE$$,$$HYDROGRAPHIE_XX$$,$$h_surf_XX$$),
($$Limite d arrondissement non représentées(?)$$,$$L$$,$$LIM_ARRONDISSEMENT$$,$$LIMITES_XX$$,$$l_admin_XX$$),
($$Limite de commune$$,$$L$$,$$LIM_COMMUNE$$,$$LIMITES_XX$$,$$l_admin_XX$$),
($$Limite de département$$,$$L$$,$$LIM_DEPARTEMENT$$,$$LIMITES_XX$$,$$l_admin_XX$$),
($$Limite d état$$,$$L$$,$$LIM_ETAT$$,$$LIMITES_XX$$,$$l_admin_XX$$),
($$Limite entre états étrangers présent 25K mais non symbo$$,$$L$$,$$LIM_ETAT_ETRANGER$$,$$LIMITES_XX$$,$$l_admin_XX$$),
($$Limite de région symbo département au 25K$$,$$L$$,$$LIM_REGION$$,$$LIMITES_XX$$,$$l_admin_XX$$),
($$Clôture$$,$$L$$,$$CLOTURE$$,$$LIMITES_XX$$,$$lim_divers_XX$$),
($$Layon plus entretenu dans BDU2?$$,$$L$$,$$LAYON$$,$$LIMITES_XX$$,$$lim_divers_XX$$),
($$Tranchée$$,$$L$$,$$TRANCHEE$$,$$LIMITES_XX$$,$$lim_divers_XX$$),
($$Camp militaire non clos$$,$$S$$,$$CAMP_MILITAIRE_NON_CLOS$$,$$LIMITES_XX$$,$$l_militaire_XX$$),
($$Champ de tir$$,$$S$$,$$CHAMP_TIR$$,$$LIMITES_XX$$,$$l_militaire_XX$$),
($$Enceinte militaire $$,$$S$$,$$ENCEINTE_MILITAIRE$$,$$LIMITES_XX$$,$$l_militaire_XX$$),
($$Zone réglementée (encore utile? Cf France25)$$,$$S$$,$$ZONE_REGLEMENTEE ?$$,$$LIMITES_XX$$,$$l_militaire_XX$$),
($$Limite de camp militaire non clos$$,$$L$$,$$LIM_CAMP_MILITAIRE_NON_CLOS$$,$$LIMITES_XX$$,$$l_militaire_lin_XX$$),
($$Limite de champ de tir$$,$$L$$,$$LIM_CHAMP_TIR$$,$$LIMITES_XX$$,$$l_militaire_lin_XX$$),
($$Limite d enceinte militaire $$,$$L$$,$$LIM_ENCEINTE_MILI$$,$$LIMITES_XX$$,$$l_militaire_lin_XX$$),
($$Limite de zone réglementée$$,$$L$$,$$LIM_ZONE_REGLEMENTEE$$,$$LIMITES_XX$$,$$l_militaire_lin_XX$$),
($$Limite de forêt domaniale$$,$$L$$,$$LIM_FORET_DOMANIALE$$,$$LIMITES_XX$$,$$l_nature_lin_XX$$),
($$Limite de parcelle forestière$$,$$L$$,$$LIM_PARCELLE_FOR$$,$$LIMITES_XX$$,$$l_nature_lin_XX$$),
($$Limite de parc national/naturel$$,$$L$$,$$LIM_PARC_NATUREL$$,$$LIMITES_XX$$,$$l_nature_lin_XX$$),
($$Limite de parc naturel (île) 100K$$,$$L$$,$$LIM_PARC_NATUREL_ILE$$,$$LIMITES_XX$$,$$l_nature_lin_XX$$),
($$Limite de parc naturel marin$$,$$L$$,$$LIM_PARC_NATUREL_MARIN$$,$$LIMITES_XX$$,$$l_nature_lin_XX$$),
($$Limite de réserve naturelle?$$,$$L$$,$$LIM_RESERVE_NATURELLE ?$$,$$LIMITES_XX$$,$$l_nature_lin_XX$$),
($$Limite de série ONF?$$,$$L$$,$$LIM_SERIE_ONF ?$$,$$LIMITES_XX$$,$$l_nature_lin_XX$$),
($$Limite de zone naturelle$$,$$L$$,$$LIM_ZONE_NATURELLE$$,$$LIMITES_XX$$,$$l_nature_lin_XX$$),
($$Limite de zone naturelle (île) 100K$$,$$L$$,$$LIM_ZONE_NATURELLE_ILE$$,$$LIMITES_XX$$,$$l_nature_lin_XX$$),
($$Limite de zone périphérique de parc (d aire d adhésion)$$,$$L$$,$$LIM_ZONE_PERI_PARC$$,$$LIMITES_XX$$,$$l_nature_lin_XX$$),
($$Limite de zone protégée?$$,$$L$$,$$LIM_ZONE_PROTEGEE ?$$,$$LIMITES_XX$$,$$l_nature_lin_XX$$),
($$Limite de zone de silence?$$,$$L$$,$$LIM_ZONE_SILENCE$$,$$LIMITES_XX$$,$$l_nature_lin_XX$$),
($$Forêt domaniale$$,$$S$$,$$FORET_DOMANIALE$$,$$LIMITES_XX$$,$$l_nature_XX$$),
($$Parcelle forestière$$,$$S$$,$$PARCELLE_FORESTIERE$$,$$LIMITES_XX$$,$$l_nature_XX$$),
($$Parc naturel$$,$$S$$,$$PARC_NATUREL$$,$$LIMITES_XX$$,$$l_nature_XX$$),
($$Parc naturel (île) 100K$$,$$S$$,$$PARC_NATUREL_ILE$$,$$LIMITES_XX$$,$$l_nature_XX$$),
($$Parc naturel marin$$,$$S$$,$$PARC_NATUREL_MARIN$$,$$LIMITES_XX$$,$$l_nature_XX$$),
($$Réserve naturelle$$,$$S$$,$$RESERVE_NATURELLE$$,$$LIMITES_XX$$,$$l_nature_XX$$),
($$Série ONF?$$,$$S$$,$$SERIE_ONF?$$,$$LIMITES_XX$$,$$l_nature_XX$$),
($$Zone naturelle$$,$$S$$,$$ZONE_NATURELLE$$,$$LIMITES_XX$$,$$l_nature_XX$$),
($$Zone naturelle (île) 100K$$,$$S$$,$$ZONE_NATURELLE_ILE$$,$$LIMITES_XX$$,$$l_nature_XX$$),
($$Zone périphérique de parc$$,$$S$$,$$ZONE_PERI_PARC$$,$$LIMITES_XX$$,$$l_nature_XX$$),
($$Zone protégée$$,$$S$$,$$ZONE_PROTEGEE$$,$$LIMITES_XX$$,$$l_nature_XX$$),
($$Zone de silence$$,$$S$$,$$ZONE_SILENCE$$,$$LIMITES_XX$$,$$l_nature_XX$$),
($$Courbe bathymétrique$$,$$L$$,$$CNV_BATHYMETRIQUE$$,$$OROGRAPHIE_XX$$,$$o_courbe_XX$$),
($$Courbe de niveau glacier intercalaire$$,$$L$$,$$CNV_GLACIER_INTERCAL$$,$$OROGRAPHIE_XX$$,$$o_courbe_XX$$),
($$Courbe de niveau glacier maîtresse$$,$$L$$,$$CNV_GLACIER_MAITRESSE$$,$$OROGRAPHIE_XX$$,$$o_courbe_XX$$),
($$Courbe de niveau glacier normale$$,$$L$$,$$CNV_GLACIER_NORMALE$$,$$OROGRAPHIE_XX$$,$$o_courbe_XX$$),
($$Courbe de niveau intercalaire$$,$$L$$,$$CNV_INTERCALAIRE$$,$$OROGRAPHIE_XX$$,$$o_courbe_XX$$),
($$Courbe de niveau maîtresse$$,$$L$$,$$CNV_MAITRESSE$$,$$OROGRAPHIE_XX$$,$$o_courbe_XX$$),
($$Courbe de niveau normale$$,$$L$$,$$CNV_NORMALE$$,$$OROGRAPHIE_XX$$,$$o_courbe_XX$$),
($$Courbe de niveau rocher intercalaire$$,$$L$$,$$CNV_ROCHER_INTERCAL$$,$$OROGRAPHIE_XX$$,$$o_courbe_XX$$),
($$Courbe de niveau rocher maîtresse$$,$$L$$,$$CNV_ROCHER_MAITRESSE$$,$$OROGRAPHIE_XX$$,$$o_courbe_XX$$),
($$Courbe de niveau rocher normale Voir Gorges du Franchar$$,$$L$$,$$CNV_ROCHER_NORMALE$$,$$OROGRAPHIE_XX$$,$$o_courbe_XX$$),
($$Courbe de niveau sous intercalaire$$,$$L$$,$$CNV_SS_INTERCALAIRE$$,$$OROGRAPHIE_XX$$,$$o_courbe_XX$$),
($$Cuvette bathymétrique$$,$$L$$,$$CUV_BATHYMETRIQUE$$,$$OROGRAPHIE_XX$$,$$o_courbe_XX$$),
($$Cuvette glacier intercalaire$$,$$L$$,$$CUV_GLACIER_INTERCAL$$,$$OROGRAPHIE_XX$$,$$o_courbe_XX$$),
($$Cuvette glacier maîtresse$$,$$L$$,$$CUV_GLACIER_MAITRESSE$$,$$OROGRAPHIE_XX$$,$$o_courbe_XX$$),
($$Cuvette glacier normale$$,$$L$$,$$CUV_GLACIER_NORMALE$$,$$OROGRAPHIE_XX$$,$$o_courbe_XX$$),
($$Cuvette intercalaire$$,$$L$$,$$CUVETTE_INTERCAL$$,$$OROGRAPHIE_XX$$,$$o_courbe_XX$$),
($$Cuvette maîtresse$$,$$L$$,$$CUVETTE_MAITRESSE$$,$$OROGRAPHIE_XX$$,$$o_courbe_XX$$),
($$Cuvette normale$$,$$L$$,$$CUVETTE_NORMALE$$,$$OROGRAPHIE_XX$$,$$o_courbe_XX$$),
($$Cuvette rocher intercalaire$$,$$L$$,$$CUV_ROCHER_INTERCAL$$,$$OROGRAPHIE_XX$$,$$o_courbe_XX$$),
($$Cuvette rocher maîtresse$$,$$L$$,$$CUV_ROCHER_MAITRESSE$$,$$OROGRAPHIE_XX$$,$$o_courbe_XX$$),
($$Cuvette rocher normale$$,$$L$$,$$CUV_ROCHER_NORMALE$$,$$OROGRAPHIE_XX$$,$$o_courbe_XX$$),
($$Carrière$$,$$L$$,$$CARRIERE_LIN$$,$$OROGRAPHIE_XX$$,$$o_ligne_XX$$),
($$Levée$$,$$L$$,$$LEVEE$$,$$OROGRAPHIE_XX$$,$$o_ligne_XX$$),
($$Talus$$,$$L$$,$$TALUS$$,$$OROGRAPHIE_XX$$,$$o_ligne_XX$$),
($$Point coté réseau 25K$$,$$P$$,$$POINT_COTE_RESEAU_25$$,$$OROGRAPHIE_XX$$,$$o_point_cote_XX$$),
($$Point coté réseau 50K$$,$$P$$,$$POINT_COTE_RESEAU_50$$,$$OROGRAPHIE_XX$$,$$o_point_cote_XX$$),
($$Point coté sommet$$,$$P$$,$$POINT_COTE_TOPO$$,$$OROGRAPHIE_XX$$,$$o_point_cote_XX$$),
($$Fond de cuvette (ajout 28/11/2018 https://amelio.ign.fr/front/ticket.form.php?id=2018112721)$$,$$P$$,$$POINT_CUVETTE$$,$$OROGRAPHIE_XX$$,$$o_point_cote_XX$$),
($$Point RBF$$,$$P$$,$$POINT_RBF$$,$$OROGRAPHIE_XX$$,$$o_point_cote_XX$$),
($$Aven$$,$$P$$,$$AVEN$$,$$OROGRAPHIE_XX$$,$$o_ponc_XX$$),
($$Bloc rocheux isolé$$,$$P$$,$$BLOC_ROCHEUX_ISOLE$$,$$OROGRAPHIE_XX$$,$$o_ponc_XX$$),
($$Cave$$,$$P$$,$$CAVE$$,$$OROGRAPHIE_XX$$,$$o_ponc_XX$$),
($$Gouffre avec Grotte au 100/250$$,$$P$$,$$GOUFFRE$$,$$OROGRAPHIE_XX$$,$$o_ponc_XX$$),
($$Grotte$$,$$P$$,$$GROTTE$$,$$OROGRAPHIE_XX$$,$$o_ponc_XX$$),
($$CAP  CIRQUE  COL  CRETE  DEPRESSION$$,$$P$$,$$?$$,$$OROGRAPHIE_XX$$,$$o_ponc_XX$$),
($$DUNE ESCARPEMENT  GORGE  ILE  MONTAGNE$$,$$P$$,$$?$$,$$OROGRAPHIE_XX$$,$$o_ponc_XX$$),
($$PIC PLAGE  PLAINE  RECIF  ROCHERS$$,$$P$$,$$?$$,$$OROGRAPHIE_XX$$,$$o_ponc_XX$$),
($$SOMMET  TERRIL  VALLEE  VERSANT  VOLCAN$$,$$P$$,$$?$$,$$OROGRAPHIE_XX$$,$$o_ponc_XX$$),
($$Autoroute/Type autoroutier/Niv 4 (25K) en construction$$,$$L$$,$$AUTOROU_CONSTR$$,$$ROUTIER_XX$$,$$r_auto_XX$$),
($$Autouroute section libre ou Type autoroutier$$,$$L$$,$$AUTOROU_LIBRE$$,$$ROUTIER_XX$$,$$r_auto_XX$$),
($$Autouroute section à péage$$,$$L$$,$$AUTOROU_PEAGE$$,$$ROUTIER_XX$$,$$r_auto_XX$$),
($$Bretelle d autoroute libre/Type autoutie 1 voie (ou 100K)$$,$$L$$,$$BRET_AUTO_LIBRE_1$$,$$ROUTIER_XX$$,$$r_auto_XX$$),
($$Bretelle d autoroute libre/Type autoutie 2 voies$$,$$L$$,$$BRET_AUTO_LIBRE_2$$,$$ROUTIER_XX$$,$$r_auto_XX$$),
($$Bretelle d autoroute libre/Type autoutier 3 voies$$,$$L$$,$$BRET_AUTO_LIBRE_3$$,$$ROUTIER_XX$$,$$r_auto_XX$$),
($$Bretelle d autoroute à péage 1 voie (ou 100K)$$,$$L$$,$$BRET_AUTO_PEAGE_1$$,$$ROUTIER_XX$$,$$r_auto_XX$$),
($$Bretelle d autoroute à péage 2 voies$$,$$L$$,$$BRET_AUTO_PEAGE_2$$,$$ROUTIER_XX$$,$$r_auto_XX$$),
($$Bretelle d autoroute à péage 3 voies$$,$$L$$,$$BRET_AUTO_PEAGE_3$$,$$ROUTIER_XX$$,$$r_auto_XX$$),
($$Passage souterrain autoroute en construction$$,$$L$$,$$AUTOROU_CONSTR_SOU$$,$$ROUTIER_XX$$,$$r_auto_sou_XX$$),
($$Passage souterrain autouroute section libre  ou Type autoroutier$$,$$L$$,$$AUTOROU_LIBRE_SOU$$,$$ROUTIER_XX$$,$$r_auto_sou_XX$$),
($$Passage souterrain autouroute section à péage$$,$$L$$,$$AUTOROU_PEAGE_SOU$$,$$ROUTIER_XX$$,$$r_auto_sou_XX$$),
($$Passage sout bretelle d autoroute libre/Type autoutier 1 voie (ou 100K)$$,$$L$$,$$BRET_AUTO_LIBRE_1_SOU$$,$$ROUTIER_XX$$,$$r_auto_sou_XX$$),
($$Passage sout bretelle d autoroute libre/Type autoutier 2 voies$$,$$L$$,$$BRET_AUTO_LIBRE_2_SOU$$,$$ROUTIER_XX$$,$$r_auto_sou_XX$$),
($$Passage sout bretelle d autoroute libre/Type autoutier 3 voies$$,$$L$$,$$BRET_AUTO_LIBRE_3_SOU$$,$$ROUTIER_XX$$,$$r_auto_sou_XX$$),
($$Passage souterrain bretelle d autoroute à péage 1 voie (ou 100K)$$,$$L$$,$$BRET_AUTO_PEAGE_1_SOU$$,$$ROUTIER_XX$$,$$r_auto_sou_XX$$),
($$Passage souterrain bretelle d autoroute à péage 2 voies$$,$$L$$,$$BRET_AUTO_PEAGE_2_SOU$$,$$ROUTIER_XX$$,$$r_auto_sou_XX$$),
($$Passage souterrain bretelle d autoroute à péage 3 voies$$,$$L$$,$$BRET_AUTO_PEAGE_3_SOU$$,$$ROUTIER_XX$$,$$r_auto_sou_XX$$),
($$Passage supérieur autoroute en construction/Type auto/Niv4$$,$$L$$,$$AUTOROU_CONSTR_SUP$$,$$ROUTIER_XX$$,$$r_auto_sup_XX$$),
($$Passage supérieur autouroute section libre ou Type autoroutier$$,$$L$$,$$AUTOROU_LIBRE_SUP$$,$$ROUTIER_XX$$,$$r_auto_sup_XX$$),
($$Passage supérieur autouroute section à péage$$,$$L$$,$$AUTOROU_PEAGE_SUP$$,$$ROUTIER_XX$$,$$r_auto_sup_XX$$),
($$Passage sup bretelle d autoroute libre/Type autoutier 1 voie (ou 100K)$$,$$L$$,$$BRET_AUTO_LIBRE_1_SUP$$,$$ROUTIER_XX$$,$$r_auto_sup_XX$$),
($$Passage sup bretelle d autoroute libre/Type autoutier 2 voies$$,$$L$$,$$BRET_AUTO_LIBRE_2_SUP$$,$$ROUTIER_XX$$,$$r_auto_sup_XX$$),
($$Passage sup bretelle d autoroute libre/Type autoutier 3 voies$$,$$L$$,$$BRET_AUTO_LIBRE_3_SUP$$,$$ROUTIER_XX$$,$$r_auto_sup_XX$$),
($$Passage supérieur bretelle d autoroute à péage 1 voie (ou 100K)$$,$$L$$,$$BRET_AUTO_PEAGE_1_SUP$$,$$ROUTIER_XX$$,$$r_auto_sup_XX$$),
($$Passage supérieur bretelle d autoroute à péage 2 voies$$,$$L$$,$$BRET_AUTO_PEAGE_2_SUP$$,$$ROUTIER_XX$$,$$r_auto_sup_XX$$),
($$Passage supérieur bretelle d autoroute à péage 3 voies$$,$$L$$,$$BRET_AUTO_PEAGE_3_SUP$$,$$ROUTIER_XX$$,$$r_auto_sup_XX$$),
($$Chemin$$,$$L$$,$$CHEMIN$$,$$ROUTIER_XX$$,$$r_chemin_XX$$),
($$Chemin de densification pas mis à niveau BDU2$$,$$L$$,$$CHEMIN_DENSIF$$,$$ROUTIER_XX$$,$$r_chemin_XX$$),
($$Escalier$$,$$L$$,$$ESCALIER$$,$$ROUTIER_XX$$,$$r_chemin_XX$$),
($$Escalier de densification pas mis à niveau BDU2$$,$$L$$,$$ESCALIER_DENSIF$$,$$ROUTIER_XX$$,$$r_chemin_XX$$),
($$Piste cyclable$$,$$L$$,$$PISTE_CYCLABLE$$,$$ROUTIER_XX$$,$$r_chemin_XX$$),
($$Piste cyclable de densification pas mis à niveau BDU2$$,$$L$$,$$PISTE_CYC_DENSIF$$,$$ROUTIER_XX$$,$$r_chemin_XX$$),
($$Rue piétonne$$,$$L$$,$$RUE_PIETONNE$$,$$ROUTIER_XX$$,$$r_chemin_XX$$),
($$Sentier$$,$$L$$,$$SENTIER$$,$$ROUTIER_XX$$,$$r_chemin_XX$$),
($$Sentier de densification pas mis à niveau BDU2$$,$$L$$,$$SENTIER_DENSIF$$,$$ROUTIER_XX$$,$$r_chemin_XX$$),
($$Sentier fictif (objets géographiques supports d itinéraires)$$,$$L$$,$$SENTIER_FICTIF$$,$$ROUTIER_XX$$,$$r_chemin_XX$$),
($$Passage souterrain chemin$$,$$L$$,$$CHEMIN_SOU$$,$$ROUTIER_XX$$,$$r_chemin_sou_XX$$),
($$Passage souterrain escalier$$,$$L$$,$$ESCALIER_SOU$$,$$ROUTIER_XX$$,$$r_chemin_sou_XX$$),
($$Passage souterrain piste cyclable$$,$$L$$,$$PISTE_CYCLABLE_SOU$$,$$ROUTIER_XX$$,$$r_chemin_sou_XX$$),
($$Passage souterrain rue piétonne$$,$$L$$,$$RUE_PIETONNE_SOU$$,$$ROUTIER_XX$$,$$r_chemin_sou_XX$$),
($$Passage souterrain sentier$$,$$L$$,$$SENTIER_SOU$$,$$ROUTIER_XX$$,$$r_chemin_sou_XX$$),
($$Passage supérieur chemin$$,$$L$$,$$CHEMIN_SUP$$,$$ROUTIER_XX$$,$$r_chemin_sup_XX$$),
($$Passage supérieur escalier$$,$$L$$,$$ESCALIER_SUP$$,$$ROUTIER_XX$$,$$r_chemin_sup_XX$$),
($$Passage supérieur piste cyclable$$,$$L$$,$$PISTE_CYCLABLE_SUP$$,$$ROUTIER_XX$$,$$r_chemin_sup_XX$$),
($$Passage supérieur rue piétonne$$,$$L$$,$$RUE_PIETONNE_SUP$$,$$ROUTIER_XX$$,$$r_chemin_sup_XX$$),
($$Passage supérieur sentier fictif$$,$$L$$,$$SENTIER_FICTIF_SUP$$,$$ROUTIER_XX$$,$$r_chemin_sup_XX$$),
($$Passage supérieur sentier$$,$$L$$,$$SENTIER_SUP$$,$$ROUTIER_XX$$,$$r_chemin_sup_XX$$),
($$Aire de repos partielle (1 côté)$$,$$P$$,$$AIRE_REPOS_PART)$$,$$ROUTIER_XX$$,$$r_equipement_XX$$),
($$Aire de repos totale (2 côtés)$$,$$P$$,$$AIRE_REPOS_TOT)$$,$$ROUTIER_XX$$,$$r_equipement_XX$$),
($$Aire de service partielle (1 côté)$$,$$P$$,$$AIRE_SERVICE_PART)$$,$$ROUTIER_XX$$,$$r_equipement_XX$$),
($$Aire de service totale (2 côtés)$$,$$P$$,$$AIRE_SERVICE_TOT$$,$$ROUTIER_XX$$,$$r_equipement_XX$$),
($$Barrière$$,$$P$$,$$BARRIERE$$,$$ROUTIER_XX$$,$$r_equipement_XX$$),
($$Echangeur partiel$$,$$P$$,$$ECHANGEUR_PART$$,$$ROUTIER_XX$$,$$r_equipement_XX$$),
($$Echangeur total$$,$$P$$,$$ECHANGEUR_TOT$$,$$ROUTIER_XX$$,$$r_equipement_XX$$),
($$Entrée/sortie de tunnel (100K)$$,$$P$$,$$ENTREE_TUNNEL_PONC$$,$$ROUTIER_XX$$,$$r_equipement_XX$$),
($$Passage à niveau$$,$$P$$,$$PASSAGE_A_NIVEAU$$,$$ROUTIER_XX$$,$$r_equipement_XX$$),
($$Péage ponctuel$$,$$P$$,$$PEAGE_PONC$$,$$ROUTIER_XX$$,$$r_equipement_XX$$),
($$Rond-point ponctuel$$,$$P$$,$$ROND_POINT_PONC$$,$$ROUTIER_XX$$,$$r_equipement_XX$$),
($$Aqueduc$$,$$L$$,$$AQUEDUC$$,$$ROUTIER_XX$$,$$r_liaison_XX$$),
($$Bac automobile$$,$$L$$,$$BAC_AUTO$$,$$ROUTIER_XX$$,$$r_liaison_XX$$),
($$Liaison maritime$$,$$L$$,$$BAC_LIAISON_MARITIME$$,$$ROUTIER_XX$$,$$r_liaison_XX$$),
($$Bac piéton$$,$$L$$,$$BAC_PIETON$$,$$ROUTIER_XX$$,$$r_liaison_XX$$),
($$Entrée de tunnel (linéaire)$$,$$L$$,$$ENTREE_TUNNEL$$,$$ROUTIER_XX$$,$$r_liaison_XX$$),
($$Gué chemin$$,$$L$$,$$GUE_CHEMIN$$,$$ROUTIER_XX$$,$$r_liaison_XX$$),
($$Gué route$$,$$L$$,$$GUE_ROUTE$$,$$ROUTIER_XX$$,$$r_liaison_XX$$),
($$Parapet de pont pour interactif sauf si ArcGIS OK$$,$$L$$,$$PARAPET$$,$$ROUTIER_XX$$,$$r_liaison_XX$$),
($$Pont linéaire (TEMP) pour calcul ET écriture$$,$$L$$,$$PONT_LIN$$,$$ROUTIER_XX$$,$$r_liaison_XX$$),
($$Pont mobile$$,$$L$$,$$PONT_MOBILE_LIN$$,$$ROUTIER_XX$$,$$r_liaison_XX$$),
($$Pont isolé ou passerelle$$,$$L$$,$$PONT_PASSERELLE$$,$$ROUTIER_XX$$,$$r_liaison_XX$$),
($$Pont transbordeur$$,$$L$$,$$PONT_TRANSBORDEUR$$,$$ROUTIER_XX$$,$$r_liaison_XX$$),
($$Viaduc BDU2$$,$$L$$,$$VIADUC$$,$$ROUTIER_XX$$,$$r_liaison_XX$$),
($$Bretelle locale (100K)$$,$$L$$,$$BRET_LOCALE$$,$$ROUTIER_XX$$,$$r_route_XX$$),
($$Bretelle principale (100K)$$,$$L$$,$$BRET_PRINCIPALE$$,$$ROUTIER_XX$$,$$r_route_XX$$),
($$Bretelle régionale (100K)$$,$$L$$,$$BRET_REGIONALE$$,$$ROUTIER_XX$$,$$r_route_XX$$),
($$Locale 1$$,$$L$$,$$LOCALE_1$$,$$ROUTIER_XX$$,$$r_route_XX$$),
($$Locale 2 (fusion  2 / 3  au 100K)$$,$$L$$,$$LOCALE_2$$,$$ROUTIER_XX$$,$$r_route_XX$$),
($$Locale 3 (ex Locale 4 sans chaussées séparées pour 100K)$$,$$L$$,$$LOCALE_3$$,$$ROUTIER_XX$$,$$r_route_XX$$),
($$Locale 4 (à chaussées séparées)$$,$$L$$,$$LOCALE_4$$,$$ROUTIER_XX$$,$$r_route_XX$$),
($$Locale en construction$$,$$L$$,$$LOCALE_CONSTR$$,$$ROUTIER_XX$$,$$r_route_XX$$),
($$Non classée$$,$$L$$,$$NON_CLASSEE$$,$$ROUTIER_XX$$,$$r_route_XX$$),
($$Non classée 4 (à chaussées séparées)$$,$$L$$,$$NON_CLASSEE_4$$,$$ROUTIER_XX$$,$$r_route_XX$$),
($$Restreint aux ayant droit$$,$$L$$,$$NON_CLASSEE_RESTREINT$$,$$ROUTIER_XX$$,$$r_route_XX$$),
($$Non revêtue carrossable$$,$$L$$,$$NON_REVETUE_CARRO$$,$$ROUTIER_XX$$,$$r_route_XX$$),
($$Principale 1$$,$$L$$,$$PRINCIPALE_1$$,$$ROUTIER_XX$$,$$r_route_XX$$),
($$Principale 2 (fusion  2 / 3  au 100K)$$,$$L$$,$$PRINCIPALE_2$$,$$ROUTIER_XX$$,$$r_route_XX$$),
($$Principale 3 (ex Principale 4 sans chaussées séparées pour 100K)$$,$$L$$,$$PRINCIPALE_3$$,$$ROUTIER_XX$$,$$r_route_XX$$),
($$Principale 4 (à chaussées séparées)$$,$$L$$,$$PRINCIPALE_4$$,$$ROUTIER_XX$$,$$r_route_XX$$),
($$Principale en construction$$,$$L$$,$$PRINCIPALE_CONSTR$$,$$ROUTIER_XX$$,$$r_route_XX$$),
($$Régionale 1$$,$$L$$,$$REGIONALE_1$$,$$ROUTIER_XX$$,$$r_route_XX$$),
($$Régionale 2 (fusion  2 / 3  au 100K)$$,$$L$$,$$REGIONALE_2$$,$$ROUTIER_XX$$,$$r_route_XX$$),
($$Régionale 3 (ex Régionale 4 sans chaussées séparées pour 100K)$$,$$L$$,$$REGIONALE_3$$,$$ROUTIER_XX$$,$$r_route_XX$$),
($$Régionale 4 (à chaussées séparées)$$,$$L$$,$$REGIONALE_4$$,$$ROUTIER_XX$$,$$r_route_XX$$),
($$Régionale en construction$$,$$L$$,$$REGIONALE_CONSTR$$,$$ROUTIER_XX$$,$$r_route_XX$$),
($$Route en construction (old=France25)$$,$$L$$,$$ROUTE_CONSTR$$,$$ROUTIER_XX$$,$$r_route_XX$$),
($$Passage souterrain bretelle locale (100K)$$,$$L$$,$$BRET_LOCALE_SOU$$,$$ROUTIER_XX$$,$$r_route_sou_XX$$),
($$Passage souterrain bretelle principale (100K)$$,$$L$$,$$BRET_PRINCIPALE_SOU$$,$$ROUTIER_XX$$,$$r_route_sou_XX$$),
($$Passage souterrain bretelle régionale (100K)$$,$$L$$,$$BRET_REGIONALE_SOU$$,$$ROUTIER_XX$$,$$r_route_sou_XX$$),
($$Passage souterrain locale 1$$,$$L$$,$$LOCALE_1_SOU$$,$$ROUTIER_XX$$,$$r_route_sou_XX$$),
($$Passage souterrain locale 2$$,$$L$$,$$LOCALE_2_SOU$$,$$ROUTIER_XX$$,$$r_route_sou_XX$$),
($$Passage souterrain locale 3$$,$$L$$,$$LOCALE_3_SOU$$,$$ROUTIER_XX$$,$$r_route_sou_XX$$),
($$Passage souterrain locale 4 (à chaussées séparées)$$,$$L$$,$$LOCALE_4_SOU$$,$$ROUTIER_XX$$,$$r_route_sou_XX$$),
($$Passage souterrain locale en construction$$,$$L$$,$$LOCALE_CONSTR_SOU$$,$$ROUTIER_XX$$,$$r_route_sou_XX$$),
($$Passage souterrain non classée 4 (à chaussées séparées)$$,$$L$$,$$NON_CLASSEE_4_SOU$$,$$ROUTIER_XX$$,$$r_route_sou_XX$$),
($$"Passage souterrain non classé ""Restreint aux ayant droit"""$$,$$L$$,$$NON_CLASSEE_RESTREINT_SOU$$,$$ROUTIER_XX$$,$$r_route_sou_XX$$),
($$Passage souterrain non classée$$,$$L$$,$$NON_CLASSEE_SOU$$,$$ROUTIER_XX$$,$$r_route_sou_XX$$),
($$Passage souterrain route non revêtue carrossable$$,$$L$$,$$NON_REVETUE_CARRO_SOU$$,$$ROUTIER_XX$$,$$r_route_sou_XX$$),
($$Passage souterrain principale 1$$,$$L$$,$$PRINCIPALE_1_SOU$$,$$ROUTIER_XX$$,$$r_route_sou_XX$$),
($$Passage souterrain principale 2  (fusion  2 / 3  au 100/200)$$,$$L$$,$$PRINCIPALE_2_SOU$$,$$ROUTIER_XX$$,$$r_route_sou_XX$$),
($$Passage souterrain principale 3$$,$$L$$,$$PRINCIPALE_3_SOU$$,$$ROUTIER_XX$$,$$r_route_sou_XX$$),
($$Passage souterrain principale 4 (à chaussées séparées)$$,$$L$$,$$PRINCIPALE_4_SOU$$,$$ROUTIER_XX$$,$$r_route_sou_XX$$),
($$Passage souterrain principale en construction$$,$$L$$,$$PRINCIPALE_CONSTR_SOU$$,$$ROUTIER_XX$$,$$r_route_sou_XX$$),
($$Passage souterrain régionale 1$$,$$L$$,$$REGIONALE_1_SOU$$,$$ROUTIER_XX$$,$$r_route_sou_XX$$),
($$Passage souterrain régionale 2$$,$$L$$,$$REGIONALE_2_SOU$$,$$ROUTIER_XX$$,$$r_route_sou_XX$$),
($$Passage souterrain régionale 3$$,$$L$$,$$REGIONALE_3_SOU$$,$$ROUTIER_XX$$,$$r_route_sou_XX$$),
($$Passage souterrain régionale 4 (à chaussées séparées)$$,$$L$$,$$REGIONALE_4_SOU$$,$$ROUTIER_XX$$,$$r_route_sou_XX$$),
($$Passage souterrain régionale en construction$$,$$L$$,$$REGIONALE_CONSTR_SOU$$,$$ROUTIER_XX$$,$$r_route_sou_XX$$),
($$Passage souterrain route en construction (old=France25)$$,$$L$$,$$ROUTE_CONSTR_SOU$$,$$ROUTIER_XX$$,$$r_route_sou_XX$$),
($$Passage supérieur bretelle locale (100K)$$,$$L$$,$$BRET_LOCALE_SUP$$,$$ROUTIER_XX$$,$$r_route_sup_XX$$),
($$Passage supérieur bretelle principale (100K)$$,$$L$$,$$BRET_PRINCIPALE_SUP$$,$$ROUTIER_XX$$,$$r_route_sup_XX$$),
($$Passage supérieur bretelle régionale (100K)$$,$$L$$,$$BRET_REGIONALE_SUP$$,$$ROUTIER_XX$$,$$r_route_sup_XX$$),
($$Passage supérieur locale 1$$,$$L$$,$$LOCALE_1_SUP$$,$$ROUTIER_XX$$,$$r_route_sup_XX$$),
($$Passage supérieur locale 2$$,$$L$$,$$LOCALE_2_SUP$$,$$ROUTIER_XX$$,$$r_route_sup_XX$$),
($$Passage supérieur locale 3 (ex 4 sans chauss. Sépa. pour 100K)$$,$$L$$,$$LOCALE_3_SUP$$,$$ROUTIER_XX$$,$$r_route_sup_XX$$),
($$Passage supérieur locale 4 (à chaussées séparées)$$,$$L$$,$$LOCALE_4_SUP$$,$$ROUTIER_XX$$,$$r_route_sup_XX$$),
($$Passage supérieur locale en construction$$,$$L$$,$$LOCALE_CONSTR_SUP$$,$$ROUTIER_XX$$,$$r_route_sup_XX$$),
($$Passage supérieur non classée 4 (à chaussées séparées)$$,$$L$$,$$NON_CLASSEE_4_SUP$$,$$ROUTIER_XX$$,$$r_route_sup_XX$$),
($$"Passage supérieur Non Classé ""Restreint aux ayant droit"""$$,$$L$$,$$NON_CLASSEE_RESTREINT_SUP$$,$$ROUTIER_XX$$,$$r_route_sup_XX$$),
($$Passage supérieur non classée$$,$$L$$,$$NON_CLASSEE_SUP$$,$$ROUTIER_XX$$,$$r_route_sup_XX$$),
($$Passage supérieur route non revêtue carrossable$$,$$L$$,$$NON_REVETUE_CARRO_SUP$$,$$ROUTIER_XX$$,$$r_route_sup_XX$$),
($$Passage supérieur principale 1$$,$$L$$,$$PRINCIPALE_1_SUP$$,$$ROUTIER_XX$$,$$r_route_sup_XX$$),
($$Passage supérieur principale 2  (fusion  2 / 3  au 100/200)$$,$$L$$,$$PRINCIPALE_2_SUP$$,$$ROUTIER_XX$$,$$r_route_sup_XX$$),
($$Passage supérieur principale 3 (ex 4 sans chauss. Sépa. pour 100K)$$,$$L$$,$$PRINCIPALE_3_SUP$$,$$ROUTIER_XX$$,$$r_route_sup_XX$$),
($$Passage supérieur principale 4 (à chaussées séparées)$$,$$L$$,$$PRINCIPALE_4_SUP$$,$$ROUTIER_XX$$,$$r_route_sup_XX$$),
($$Passage supérieur principale en construction$$,$$L$$,$$PRINCIPALE_CONSTR_SUP$$,$$ROUTIER_XX$$,$$r_route_sup_XX$$),
($$Passage supérieur régionale 1$$,$$L$$,$$REGIONALE_1_SUP$$,$$ROUTIER_XX$$,$$r_route_sup_XX$$),
($$Passage supérieur régionale 2$$,$$L$$,$$REGIONALE_2_SUP$$,$$ROUTIER_XX$$,$$r_route_sup_XX$$),
($$Passage supérieur régionale 3 (ex 4 sans chauss. Sépa. pour 100K)$$,$$L$$,$$REGIONALE_3_SUP$$,$$ROUTIER_XX$$,$$r_route_sup_XX$$),
($$Passage supérieur régionale 4 (à chaussées séparées)$$,$$L$$,$$REGIONALE_4_SUP$$,$$ROUTIER_XX$$,$$r_route_sup_XX$$),
($$Passage supérieur régionale en construction$$,$$L$$,$$REGIONALE_CONSTR_SUP$$,$$ROUTIER_XX$$,$$r_route_sup_XX$$),
($$Passage supérieur route en construction (old=France25)$$,$$L$$,$$ROUTE_CONSTR_SUP$$,$$ROUTIER_XX$$,$$r_route_sup_XX$$),
($$Carrefour Hors 25K$$,$$S$$,$$CARREFOUR$$,$$ROUTIER_XX$$,$$r_surf_XX$$),
($$Dalle de protection$$,$$S$$,$$DALLE_DE_PROTECTION$$,$$ROUTIER_XX$$,$$r_surf_XX$$),
($$Dalle urbaine$$,$$S$$,$$DALLE_URBAINE$$,$$ROUTIER_XX$$,$$r_surf_XX$$),
($$Escalier surfacique$$,$$S$$,$$ESCALIER_SURF$$,$$ROUTIER_XX$$,$$r_surf_XX$$),
($$Parking surfacique Hors 25K$$,$$S$$,$$PARKING_SURF$$,$$ROUTIER_XX$$,$$r_surf_XX$$),
($$Zone de péage$$,$$S$$,$$SURF_PEAGE$$,$$ROUTIER_XX$$,$$r_surf_XX$$),
($$Surface routière locale (Carrefour ou péage non autoroutier)$$,$$S$$,$$SURF_ROUT_LOC$$,$$ROUTIER_XX$$,$$r_surf_XX$$),
($$Surface routière non classée (Carrefour ou péage non autoroutier)$$,$$S$$,$$SURF_ROUT_NON_CLA$$,$$ROUTIER_XX$$,$$r_surf_XX$$),
($$Surface routière principale (Carrefour ou péage non autoroutier)$$,$$S$$,$$SURF_ROUT_PRINC$$,$$ROUTIER_XX$$,$$r_surf_XX$$),
($$Surface routière régionale (Carrefour ou péage non autoroutier)$$,$$S$$,$$SURF_ROUT_REG$$,$$ROUTIER_XX$$,$$r_surf_XX$$),
($$$$,$$NULL$$,$$NULL$$,$$ROUTIER_XX$$,$$r_surf_XX$$),
($$Poteau de balisage Conseil Général 04$$,$$P$$,$$BALISAGE_04$$,$$TOURISTIQUE_XX$$,$$t_balisage_XX$$),
($$Poteau de balisage Conseil Général 06$$,$$P$$,$$BALISAGE_06$$,$$TOURISTIQUE_XX$$,$$t_balisage_XX$$),
($$Poteau de balisage Conseil Général 84$$,$$P$$,$$BALISAGE_84$$,$$TOURISTIQUE_XX$$,$$t_balisage_XX$$),
($$Picto St Jacques de Compostelle$$,$$P$$,$$COMPOSTELLE$$,$$TOURISTIQUE_XX$$,$$t_balisage_XX$$),
($$Picto Club Vosgien XX$$,$$P$$,$$??$$,$$TOURISTIQUE_XX$$,$$t_balisage_XX$$),
($$Picto 25 Bosses…$$,$$P$$,$$?? = BALISAGE_06 pour l instant$$,$$TOURISTIQUE_XX$$,$$t_balisage_XX$$),
($$Chemin des châteaux-forts d Alsace$$,$$P$$,$$??$$,$$TOURISTIQUE_XX$$,$$t_balisage_XX$$),
($$Sentier de découverte ou parcours sportif$$,$$L$$,$$ITI_DECOUV_SPORT$$,$$TOURISTIQUE_XX$$,$$t_itineraire_XX$$),
($$Passage délicat pédestre$$,$$L$$,$$ITI_DELICAT_PEDESTRE$$,$$TOURISTIQUE_XX$$,$$t_itineraire_XX$$),
($$Passage délicat à ski$$,$$L$$,$$ITI_DELICAT_SKI$$,$$TOURISTIQUE_XX$$,$$t_itineraire_XX$$),
($$Sentier Denecourt$$,$$L$$,$$ITI_DENECOURT$$,$$TOURISTIQUE_XX$$,$$t_itineraire_XX$$),
($$Itinéraire équestre$$,$$L$$,$$ITI_EQUESTRE$$,$$TOURISTIQUE_XX$$,$$t_itineraire_XX$$),
($$Itinéraire ferré touristique$$,$$L$$,$$ITI_FERRE$$,$$TOURISTIQUE_XX$$,$$t_itineraire_XX$$),
($$Itinéraire de Grande Randonnée (GR) GR/GRP/sur et hors sentier$$,$$L$$,$$ITI_GR_GRP$$,$$TOURISTIQUE_XX$$,$$t_itineraire_XX$$),
($$Itinéraire de randonnée local Autre et hors sentier pédestre$$,$$L$$,$$ITI_LOCAL$$,$$TOURISTIQUE_XX$$,$$t_itineraire_XX$$),
($$Itinéraire de Petite Randonnée ou Club Vosgien PR/CV/sur et hors sentier$$,$$L$$,$$ITI_PDIPR_CV$$,$$TOURISTIQUE_XX$$,$$t_itineraire_XX$$),
($$Itinéraire de ski de randonnée$$,$$L$$,$$ITI_SKI_RANDO$$,$$TOURISTIQUE_XX$$,$$t_itineraire_XX$$),
($$Itinéraire voie verte$$,$$L$$,$$ITI_VOIE_VERTE$$,$$TOURISTIQUE_XX$$,$$t_itineraire_XX$$),
($$Surcharge Remontée fonctionnant l été$$,$$L$$,$$SURCH_ETE$$,$$TOURISTIQUE_XX$$,$$t_itineraire_XX$$),
($$Baignade surveillée$$,$$P$$,$$BAIGNADE_SURVEILLEE$$,$$TOURISTIQUE_XX$$,$$t_loisirs_XX$$),
($$Centre équestre$$,$$P$$,$$CENTRE_EQUESTRE$$,$$TOURISTIQUE_XX$$,$$t_loisirs_XX$$),
($$Char à voile$$,$$P$$,$$CHAR_A_VOILE$$,$$TOURISTIQUE_XX$$,$$t_loisirs_XX$$),
($$Départ de ski de fond$$,$$P$$,$$DEPART_SKI_FOND$$,$$TOURISTIQUE_XX$$,$$t_loisirs_XX$$),
($$Echelle$$,$$P$$,$$ECHELLE$$,$$TOURISTIQUE_XX$$,$$t_loisirs_XX$$),
($$Golf$$,$$P$$,$$GOLF$$,$$TOURISTIQUE_XX$$,$$t_loisirs_XX$$),
($$Hippodrome objet 25 : piste de sport$$,$$P$$,$$HIPPODROME$$,$$TOURISTIQUE_XX$$,$$t_loisirs_XX$$),
($$Parc de type jardin$$,$$P$$,$$PARC_JARDIN$$,$$TOURISTIQUE_XX$$,$$t_loisirs_XX$$),
($$Parc de loisir$$,$$P$$,$$PARC_LOISIR$$,$$TOURISTIQUE_XX$$,$$t_loisirs_XX$$),
($$Pelote basque$$,$$P$$,$$PELOTE_BASQUE$$,$$TOURISTIQUE_XX$$,$$t_loisirs_XX$$),
($$Planche à voile$$,$$P$$,$$PLANCHE_A_VOILE$$,$$TOURISTIQUE_XX$$,$$t_loisirs_XX$$),
($$Plongée$$,$$P$$,$$PLONGEE$$,$$TOURISTIQUE_XX$$,$$t_loisirs_XX$$),
($$Port de plaisance$$,$$P$$,$$PORT_PLAISANCE$$,$$TOURISTIQUE_XX$$,$$t_loisirs_XX$$),
($$Site d escalade$$,$$P$$,$$SITE_ESCALADE$$,$$TOURISTIQUE_XX$$,$$t_loisirs_XX$$),
($$Site de vol libre$$,$$P$$,$$SITE_VOL_LIBRE$$,$$TOURISTIQUE_XX$$,$$t_loisirs_XX$$),
($$Ski nautique$$,$$P$$,$$SKI_NAUTIQUE$$,$$TOURISTIQUE_XX$$,$$t_loisirs_XX$$),
($$Sports en eau vive$$,$$P$$,$$SPORTS_EAUX_VIVES$$,$$TOURISTIQUE_XX$$,$$t_loisirs_XX$$),
($$Sports nautiques$$,$$P$$,$$SPORTS_NAUTIQUES$$,$$TOURISTIQUE_XX$$,$$t_loisirs_XX$$),
($$Surf$$,$$P$$,$$SURF$$,$$TOURISTIQUE_XX$$,$$t_loisirs_XX$$),
($$Via ferrata$$,$$P$$,$$VIA_FERRATA$$,$$TOURISTIQUE_XX$$,$$t_loisirs_XX$$),
($$Voile$$,$$P$$,$$VOILE$$,$$TOURISTIQUE_XX$$,$$t_loisirs_XX$$),
($$Abri$$,$$P$$,$$ABRI$$,$$TOURISTIQUE_XX$$,$$t_ponc_XX$$),
($$Aire de détente$$,$$P$$,$$AIRE_DETENTE$$,$$TOURISTIQUE_XX$$,$$t_ponc_XX$$),
($$Arbre remarquable$$,$$P$$,$$ARBRE_REMARQUABLE$$,$$TOURISTIQUE_XX$$,$$t_ponc_XX$$),
($$Auberge de jeunesse$$,$$P$$,$$AUBERGE_JEUNESSE$$,$$TOURISTIQUE_XX$$,$$t_ponc_XX$$),
($$Belvédère$$,$$P$$,$$BELVEDERE$$,$$TOURISTIQUE_XX$$,$$t_ponc_XX$$),
($$Bergerie$$,$$P$$,$$BERGERIE$$,$$TOURISTIQUE_XX$$,$$t_ponc_XX$$),
($$Cabane$$,$$P$$,$$CABANE$$,$$TOURISTIQUE_XX$$,$$t_ponc_XX$$),
($$Camping$$,$$P$$,$$CAMPING$$,$$TOURISTIQUE_XX$$,$$t_ponc_XX$$),
($$Curiosité 25 : surcouche étoile  étoile+DES au 100/250$$,$$P$$,$$CURIOSITE$$,$$TOURISTIQUE_XX$$,$$t_ponc_XX$$),
($$Édifice remarquable$$,$$P$$,$$EDIFICE_REMARQUABLE$$,$$TOURISTIQUE_XX$$,$$t_ponc_XX$$),
($$Gîte équestre$$,$$P$$,$$GITE_EQUESTRE$$,$$TOURISTIQUE_XX$$,$$t_ponc_XX$$),
($$Gîte d étape$$,$$P$$,$$GITE_ETAPE$$,$$TOURISTIQUE_XX$$,$$t_ponc_XX$$),
($$Panorama (reste au 250K pour l instant)$$,$$P$$,$$PANORAMA$$,$$TOURISTIQUE_XX$$,$$t_ponc_XX$$),
($$Parking touristique$$,$$P$$,$$PARKING_PONC$$,$$TOURISTIQUE_XX$$,$$t_ponc_XX$$),
($$Point de vue (dont ancien PANORAMA pour 25K)$$,$$P$$,$$POINT_DE_VUE$$,$$TOURISTIQUE_XX$$,$$t_ponc_XX$$),
($$Point d information touristique isolé$$,$$P$$,$$POINT_INFO_ISOLE$$,$$TOURISTIQUE_XX$$,$$t_ponc_XX$$),
($$Refuge non gardé$$,$$P$$,$$REFUGE$$,$$TOURISTIQUE_XX$$,$$t_ponc_XX$$),
($$Refuge gardé$$,$$P$$,$$REFUGE_GARDE$$,$$TOURISTIQUE_XX$$,$$t_ponc_XX$$),
($$Table d orientation$$,$$P$$,$$TABLE_ORIENTATION = POINT_DE_VUE$$,$$TOURISTIQUE_XX$$,$$t_ponc_XX$$),
($$Blason point d information touristique Office de tourisme au 100$$,$$P$$,$$B_INFO_TOUR$$,$$TOURISTIQUE_XX$$,$$t_blason_XX$$),
($$Blason ville d art$$,$$P$$,$$B_VILLE_ART$$,$$TOURISTIQUE_XX$$,$$t_blason_XX$$),
($$Blason ville verte$$,$$P$$,$$B_STATION_VERTE$$,$$TOURISTIQUE_XX$$,$$t_blason_XX$$),
($$Blason station balnéaire$$,$$P$$,$$B_STATION_BALNEAIRE$$,$$TOURISTIQUE_XX$$,$$t_blason_XX$$),
($$Blason station de sports d hiver$$,$$P$$,$$B_STATION_SKI$$,$$TOURISTIQUE_XX$$,$$t_blason_XX$$),
($$Blason station thermale$$,$$P$$,$$B_STATION_THERMALE$$,$$TOURISTIQUE_XX$$,$$t_blason_XX$$),
($$Blason ensemble classé$$,$$P$$,$$B_ENSEMBLE_CLASSE$$,$$TOURISTIQUE_XX$$,$$t_blason_XX$$),
($$Musée Voir avec 100 : blason + petite étoile curiosité$$,$$P$$,$$B_MUSEE$$,$$TOURISTIQUE_XX$$,$$t_blason_XX$$),
($$Surlignement touristique édifice remarquable surfacique (Verdun  Paris) interactif$$,$$S$$,$$EDIFICE_REMARQUABLE_SURF$$,$$TOURISTIQUE_XX$$,$$t_surf_XX$$),
($$Barre rocheuse isolée$$,$$L$$,$$BARRE_ROCH_ISOLEE$$,$$OCCUPATION_DU_SOL_XX$$,$$v_ligne_XX$$),
($$Coulée d éboulis$$,$$L$$,$$COULEE_EBOULIS$$,$$OCCUPATION_DU_SOL_XX$$,$$v_ligne_XX$$),
($$Crevasse$$,$$L$$,$$CREVASSE$$,$$OCCUPATION_DU_SOL_XX$$,$$v_ligne_XX$$),
($$Ligne descriptive en zone rocheuse$$,$$L$$,$$LIGNE_DESC_ZONE_ROCHEUSE$$,$$OCCUPATION_DU_SOL_XX$$,$$v_ligne_XX$$),
($$Fond de cuvette humide$$,$$S$$,$$FOND_CUVETTE_HUMIDE$$,$$OCCUPATION_DU_SOL_XX$$,$$v_nature_du_sol_XX$$),
($$Surface de graviers ou galets humides$$,$$S$$,$$GRAVIERS_GALETS_HUM$$,$$OCCUPATION_DU_SOL_XX$$,$$v_nature_du_sol_XX$$),
($$Surface de graviers ou galets secs$$,$$S$$,$$GRAVIERS_GALETS_SEC$$,$$OCCUPATION_DU_SOL_XX$$,$$v_nature_du_sol_XX$$),
($$Lapiaz$$,$$S$$,$$LAPIAZ$$,$$OCCUPATION_DU_SOL_XX$$,$$v_nature_du_sol_XX$$),
($$Récif de corail$$,$$S$$,$$RECIF_CORAIL$$,$$OCCUPATION_DU_SOL_XX$$,$$v_nature_du_sol_XX$$),
($$Surface d éboulis de forte/faible pente$$,$$S$$,$$ZONE_EBOULIS$$,$$OCCUPATION_DU_SOL_XX$$,$$v_nature_du_sol_XX$$),
($$Zone de glacier pas ds BDU > Intercatif courbes raster$$,$$S$$,$$ZONE_GLACIER$$,$$OCCUPATION_DU_SOL_XX$$,$$v_nature_du_sol_XX$$),
($$Zone ravinée$$,$$S$$,$$ZONE_RAVINEE$$,$$OCCUPATION_DU_SOL_XX$$,$$v_nature_du_sol_XX$$),
($$Zone de rocher hydro$$,$$S$$,$$ZONE_ROCHER_HYDRO$$,$$OCCUPATION_DU_SOL_XX$$,$$v_nature_du_sol_XX$$),
($$Zone rocheuse  de forte/faible pente Voir Gorges du Franchar$$,$$S$$,$$ZONE_ROCHEUSE$$,$$OCCUPATION_DU_SOL_XX$$,$$v_nature_du_sol_XX$$),
($$Zone de sable humide ou vase$$,$$S$$,$$ZONE_SABLE_HUMIDE$$,$$OCCUPATION_DU_SOL_XX$$,$$v_nature_du_sol_XX$$),
($$Zone de sable sec$$,$$S$$,$$ZONE_SABLE_SEC$$,$$OCCUPATION_DU_SOL_XX$$,$$v_nature_du_sol_XX$$),
($$Houblonnière$$,$$S$$,$$HOUBLONNIERE$$,$$OCCUPATION_DU_SOL_XX$$,$$v_vegetation_XX$$),
($$Zone boisée$$,$$S$$,$$ZONE_BOISEE$$,$$OCCUPATION_DU_SOL_XX$$,$$v_vegetation_XX$$),
($$Zone de canne à sucre ou bananeraie$$,$$S$$,$$ZONE_CANNE_BANANE$$,$$OCCUPATION_DU_SOL_XX$$,$$v_vegetation_XX$$),
($$Zone de forêt fermée de conifères$$,$$S$$,$$ZONE_FORET_FERMEE_CONI$$,$$OCCUPATION_DU_SOL_XX$$,$$v_vegetation_XX$$),
($$Zone de forêt fermée de feuillus$$,$$S$$,$$ZONE_FORET_FERMEE_FEUIL$$,$$OCCUPATION_DU_SOL_XX$$,$$v_vegetation_XX$$),
($$Zone de forêt fermée mixte$$,$$S$$,$$ZONE_FORET_FERMEE_MIXTE$$,$$OCCUPATION_DU_SOL_XX$$,$$v_vegetation_XX$$),
($$Zone de forêt ouverte$$,$$S$$,$$ZONE_FORET_OUVERTE$$,$$OCCUPATION_DU_SOL_XX$$,$$v_vegetation_XX$$),
($$Zone de lande ligneuse$$,$$S$$,$$ZONE_LANDE_LIGNEUSE$$,$$OCCUPATION_DU_SOL_XX$$,$$v_vegetation_XX$$),
($$Zone de mangrove$$,$$S$$,$$ZONE_MANGROVE$$,$$OCCUPATION_DU_SOL_XX$$,$$v_vegetation_XX$$),
($$Zone de peupleraie$$,$$S$$,$$ZONE_PEUPLERAIE$$,$$OCCUPATION_DU_SOL_XX$$,$$v_vegetation_XX$$),
($$Zone de vergers avec Vigne dans données ini 100$$,$$S$$,$$ZONE_VERGER$$,$$OCCUPATION_DU_SOL_XX$$,$$v_vegetation_XX$$),
($$Zone de vigne$$,$$S$$,$$ZONE_VIGNE$$,$$OCCUPATION_DU_SOL_XX$$,$$v_vegetation_XX$$);
SELECT * FROM "x_inca_xx";
